[build]
  publish = "."

[[redirects]]
  from = "/styles.css"
  to = "/styles.css"
  status = 200

[[redirects]]
  from = "/script.js" 
  to = "/script.js"
  status = 200

[[redirects]]
  from = "/agency.js"
  to = "/agency.js"
  status = 200

[[redirects]]
  from = "/feed.js"
  to = "/feed.js"
  status = 200

[[redirects]]
  from = "/:ntdid/:mode"
  to = "/feed.html"
  status = 200

[[redirects]]
  from = "/:ntdid"
  to = "/agency.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404